### ISSUE TITLE
Is it works at opencms 9.5?

### ISSUE THREAD

**Issue by twofisher** [componio/nbDriva#1]
nbDriva is a useful plugin for NetBeans user who want to develope opencms module,thanks for you work! 

Is it works for opencms 9.5?

thanks

**Comment by ghost** [comment]
The plugin works for OpenCms 9.5.0 and with 9.5.1 it works also with the 
9.5.0 API.

**Comment by ghost** [comment]
The plugin works for OpenCms 9.5.0 and with 9.5.1, but with the 9.5.0 API.

**Comment by ghost** [comment]
If you create a new project you can choose the OpenCms version.

**Comment by ghost** [comment]
We have to update the Documentation.
Why doesn't it work for you?
Can you describe your steps for the installation and usage in more detail?
